#!/usr/bin/python

import sys
import os
import subprocess
import string
import time
import json
import tarfile
import sys
import urllib
import os
from subprocess import Popen

self = os.path.dirname(os.path.realpath(__file__))

target = 'linux'
if sys.platform == 'darwin':
    target = 'osx'

version = '3.2.1'

print 'os: %s, version: %s' % (target, version)

sitl_host = 'http://d3jdmgrrydviou.cloudfront.net'
sitl_file = "{}/copter/sitl-{}-v{}.tar.gz".format(sitl_host, target, version)

if not os.path.isdir(self + '/sitl'):
    print "Downloading SITL."

    testfile = urllib.URLopener()
    testfile.retrieve(sitl_file, self + '/sitl.tar.gz')

    tar = tarfile.open(self + '/sitl.tar.gz')
    tar.extractall(path=self + '/sitl')
    tar.close()

    print 'Extracted.'
else:
    print "SITL already Downloaded."

args = [self + '/sitl/ArduCopter.elf'] + sys.argv[1:]
print 'Execute: ' + str(args)

p = Popen(args, cwd=self)
p.communicate()
