#!/usr/bin/python

from __future__ import print_function
import re
import sys
import os
from dronekit_sitl_runner import *

system = 'copter'
target = detect_target()
version = '3.2.1'

args = sys.argv[1:]
if len(args) > 0 and args[0] == '--list':
    versions = version_list()
    for system in [system for system, v in versions.iteritems()]:
        keys = [k for k, v in versions[system].iteritems()]
        keys.sort()
        for k in keys:
            print(system + '-' + k)
    sys.exit(0)

if len(args) > 0 and args[0] == '--reset':
    reset()
    sys.exit(0)

if len(args) < 1 or not re.match(r'^(copter|plane)(-v?.+)?', args[0]):
    print('Please specify one of:', file=sys.stderr)
    print('  dronekit-sitl --list', file=sys.stderr)
    print('  dronekit-sitl --reset', file=sys.stderr)
    print('  dronekit-sitl <copter(-version)>', file=sys.stderr)
    print('  dronekit-sitl <plane(-version)>', file=sys.stderr)
    sys.exit(1)

if re.match(r'^copter-v?(.+)', args[0]):
    system = 'copter'
    version = re.match(r'^copter-v?(.+)', args[0]).group(1)
if re.match(r'^plane-v?(.+)', args[0]):
    system = 'plane'
    version = re.match(r'^plane-v?(.+)', args[0]).group(1)
args = args[1:]

print('os: %s, apm: %s, release: %s' % (target, system, version))

download(system, version, target)
launch(system, version, args)
